"""Download the site's webfonts from Google and rewrite them as self-hosted @font-face rules.

Run from the repository root:  python tools/fetch-fonts.py

Nothing on konta.md may make a visitor's browser talk to a third party, see the transparency
page. That means the fonts ship with the site rather than being linked. This script is how
assets/fonts.css and assets/fonts/ are produced; it is not part of serving the site.
"""

import io
import os
import re
import urllib.request

QUERY = (
    'https://fonts.googleapis.com/css2'
    '?family=Literata:opsz,wght@7..72,500;7..72,600'
    '&family=IBM+Plex+Sans:wght@400;500;600'
    '&display=swap'
)

# Romanian needs latin-ext (ș, ț, ă, î, â); Russian needs both cyrillic subsets. Greek and
# Vietnamese are dropped, they are a third of the bytes and nothing on the site uses them.
SUBSETS = ('latin', 'latin-ext', 'cyrillic', 'cyrillic-ext')

# Google serves one variable file per subset, so the weights below collapse onto one download.
WEIGHT_RANGE = {'IBM Plex Sans': '400 600', 'Literata': '500 600'}

UA = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36'}


def fetch(url):
    return urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=60).read()


def main():
    css = fetch(QUERY).decode('utf-8')
    blocks = re.findall(r'/\*\s*([a-z0-9-]+)\s*\*/\s*(@font-face\s*\{.*?\})', css, re.S)

    os.makedirs('assets/fonts', exist_ok=True)
    rules, done, total = [], {}, 0

    for subset, block in blocks:
        if subset not in SUBSETS:
            continue
        family = re.search(r"font-family: '([^']+)'", block).group(1)
        url = re.search(r'url\((https://[^)]+)\)', block).group(1)
        key = (family, subset)
        if key in done:
            continue

        name = '%s-%s.woff2' % (family.lower().replace(' ', ''), subset)
        data = fetch(url)
        io.open('assets/fonts/' + name, 'wb').write(data)
        done[key] = name
        total += len(data)

        rules.append(
            '/* %s */\n@font-face {\n'
            "  font-family: '%s';\n"
            '  font-style: normal;\n'
            '  font-weight: %s;\n'
            '  font-display: swap;\n'
            '  src: url(fonts/%s) format(\'woff2\');\n'
            '  unicode-range: %s;\n}'
            % (subset, family, WEIGHT_RANGE[family], name,
               re.search(r'unicode-range: ([^;]+);', block).group(1))
        )

    header = (
        '/* Generated by tools/fetch-fonts.py. Do not edit by hand.\n'
        '   Self-hosted so that loading konta.md sends no request to anyone but konta.md. */\n\n'
    )
    io.open('assets/fonts.css', 'w', encoding='utf-8', newline='\n').write(header + '\n\n'.join(rules) + '\n')
    print('%d files, %.0f KB' % (len(done), total / 1024))


if __name__ == '__main__':
    main()
